In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2],
            [3, 4]
            ])

In [4]:
print(A)

[[1 2]
 [3 4]]


In [5]:
print(A * 3)

[[ 3  6]
 [ 9 12]]


In [6]:
print(A + A)

[[2 4]
 [6 8]]


In [7]:
print(A - A)

[[0 0]
 [0 0]]


In [8]:
print(A ** 2)

[[ 1  4]
 [ 9 16]]


In [9]:
print(3 ** A)

[[ 3  9]
 [27 81]]


In [10]:
print(A * A)

[[ 1  4]
 [ 9 16]]


In [11]:
x = np.array([[1,2], [3,4]])
y = np.array([[3, 4], [3, 2]])

In [12]:
# 진짜 행렬 곱
print(np.dot(x, y))

[[ 9  8]
 [21 20]]


In [13]:
# 그냥 단순하게 계산한 것
print(x * y)

[[3 8]
 [9 8]]


#### 비교연산
* 빠르게 비교 가능

In [17]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

In [18]:
print(a == b)
print(a > b)

[False  True False  True]
[False False  True False]


#### 논리연산